// flow-typed signature: 309ede1f03786ea4324b049666fe5aa0
// flow-typed version: <<STUB>>/is-json_v2.x.x/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-json/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-json/index' {
  declare module.exports: $Exports<'is-json'>;
}
declare module 'is-json/index.js' {
  declare module.exports: $Exports<'is-json'>;
}
declare module 'is-json/test/index.js' {
  declare module.exports: $Exports<'is-json/test/index'>;
}
