/* @flow */
// flow-typed signature: 7c7bbc6f0aa1bfe7f10469b6ec6c47d3
// flow-typed version: <<STUB>>/p-event_v1.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'p-event/index' {
  declare module.exports: $Exports<'p-event'>;
}
declare module 'p-event/index.js' {
  declare module.exports: $Exports<'p-event'>;
}
